loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 181, in _packet_in_handler
    src_match = IPNetwork(self.lan_ip_subnet[dpid])
KeyError: 1
switch connected 2
switch connected 1
switch connected 16
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.2.2'
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 2
switch connected 1
switch connected 16
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.2.2'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.2.3'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.2.2'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.2.3'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.1.2'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.1.3'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.1.2'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.1.3'
switch connected 1
switch connected 16
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 181, in _packet_in_handler
    src_match = IPNetwork(self.lan_ip_subnet[dpid])
KeyError: 2
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 181, in _packet_in_handler
    src_match = IPNetwork(self.lan_ip_subnet[dpid])
KeyError: 16
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 181, in _packet_in_handler
    src_match = IPNetwork(self.lan_ip_subnet[dpid])
KeyError: 16
switch connected 2
switch connected 1
switch connected 16
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.2.2'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.2.3'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.2.2'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.2.3'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.1.2'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.1.3'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.1.2'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.1.3'
switch connected 1
switch connected 16
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 1
switch connected 2
switch connected 16
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.2.2'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.2.3'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.2.2'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.2.3'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.1.2'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.1.3'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.1.2'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.1.3'
switch connected 1
switch connected 16
switch connected 2
switch connected 1
switch connected 16
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 16
switch connected 1
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 16
switch connected 2
switch connected 1
switch connected 16
switch connected 1
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 1
switch connected 16
switch connected 2
switch connected 1
switch connected 16
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 1
switch connected 2
switch connected 16
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 208, in _packet_in_handler
    if IPAddress(ip.src) in IPNetwork(self.lan_ip_subnet[dpid]) and IPAddress(ip.dst) in IPNetwork(self.lan_ip_subnet[dpid]):
AttributeError: 'NoneType' object has no attribute 'src'
switch connected 1
switch connected 16
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 2
switch connected 1
switch connected 16
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.2.2'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 346, in _packet_in_handler
    parser.OFPActionSetDlDst(MAC_ADDR[ip.dst]),
KeyError: '192.168.2.3'
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 1
switch connected 2
switch connected 16
switch connected 1
switch connected 16
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 16
switch connected 1
switch connected 2
switch connected 16
switch connected 1
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 1
switch connected 16
switch connected 2
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 208, in _packet_in_handler
    if IPAddress(ip.src) in IPNetwork(self.lan_ip_subnet[dpid]) and IPAddress(ip.dst) in IPNetwork(self.lan_ip_subnet[dpid]):
AttributeError: 'NoneType' object has no attribute 'src'
switch connected 1
switch connected 16
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 16
switch connected 1
switch connected 2
switch connected 1
switch connected 16
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 16
switch connected 2
switch connected 1
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 208, in _packet_in_handler
    if IPAddress(ip.src) in IPNetwork(self.lan_ip_subnet[dpid]) and IPAddress(ip.dst) in IPNetwork(self.lan_ip_subnet[dpid]):
AttributeError: 'NoneType' object has no attribute 'src'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 208, in _packet_in_handler
    if IPAddress(ip.src) in IPNetwork(self.lan_ip_subnet[dpid]) and IPAddress(ip.dst) in IPNetwork(self.lan_ip_subnet[dpid]):
AttributeError: 'NoneType' object has no attribute 'src'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 208, in _packet_in_handler
    if IPAddress(ip.src) in IPNetwork(self.lan_ip_subnet[dpid]) and IPAddress(ip.dst) in IPNetwork(self.lan_ip_subnet[dpid]):
AttributeError: 'NoneType' object has no attribute 'src'
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 208, in _packet_in_handler
    if IPAddress(ip.src) in IPNetwork(self.lan_ip_subnet[dpid]) and IPAddress(ip.dst) in IPNetwork(self.lan_ip_subnet[dpid]):
AttributeError: 'NoneType' object has no attribute 'src'
switch connected 16
switch connected 1
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 1
switch connected 2
switch connected 16
switch connected 1
switch connected 16
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 1
switch connected 2
switch connected 16
switch connected 1
switch connected 16
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 1
switch connected 2
switch connected 16
switch connected 1
switch connected 16
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 16
switch connected 2
switch connected 1
NAT: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/prac_4/ryu-nat/ryu-nat.py", line 208, in _packet_in_handler
    if IPAddress(ip.src) in IPNetwork(self.lan_ip_subnet[dpid]) and IPAddress(ip.dst) in IPNetwork(self.lan_ip_subnet[dpid]):
AttributeError: 'NoneType' object has no attribute 'src'
switch connected 16
switch connected 1
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 1
switch connected 2
switch connected 16
switch connected 1
switch connected 16
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 16
switch connected 2
switch connected 1
switch connected 16
switch connected 1
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 16
switch connected 2
switch connected 1
switch connected 16
switch connected 1
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 16
switch connected 2
switch connected 1
switch connected 16
switch connected 1
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 16
switch connected 1
switch connected 2
switch connected 16
switch connected 1
switch connected 2
loading app ryu-nat/ryu-nat.py
loading app ryu.controller.dpset
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.dpset of DPSet
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu-nat/ryu-nat.py of NAT
switch connected 1
switch connected 16
switch connected 2
switch connected 1
switch connected 16
switch connected 2
